---
dist: bionic
os: linux
language: python
services:
  - docker

env:
  jobs:
    - ROLE=Rocket.Chat.Ansible MOLECULE_DISTRO=centos:7 MOLECULE_SERVICE_MANAGER=systemd MOLECULE_COMMAND=/usr/sbin/init
    - ROLE=Rocket.Chat.Ansible MOLECULE_DISTRO=centos:8 MOLECULE_SERVICE_MANAGER=systemd MOLECULE_COMMAND=/usr/sbin/init
    - ROLE=Rocket.Chat.Ansible MOLECULE_DISTRO=ubuntu:18.04 MOLECULE_SERVICE_MANAGER=systemd MOLECULE_COMMAND=/lib/systemd/systemd
    - ROLE=Rocket.Chat.Ansible MOLECULE_DISTRO=ubuntu:20.04 MOLECULE_SERVICE_MANAGER=systemd MOLECULE_COMMAND=/lib/systemd/systemd

jobs:
  fast_finish: true
install:
  - pip install molecule yamllint ansible-lint docker

script:
  - molecule test --scenario-name $ROLE

#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
